### ISSUE TITLE
[US-8]En tant qu'utilisateur connecté, je veux pouvoir laisser des commentaires et un avis noté sur les recettes que j'ai testées pour partager mes impressions avec la communauté

### ISSUE THREAD

**Issue by Samaze123** [Zwarmex/Project-dev-3#10]
# Quel est la valeur de la US pour le client
> ## Faible

# Description et objectif
> ## L'utilisateur aura la possibilité de laisser un commentaire sur l'impression qu'il a eut d'une recette, via un champ textuel ou via un avis étoilé.

# 1.0 Commentaire des recettes :
> ## En arrivant connecté sur le site web, l'utilisateur pourra visiter le profil d'autres utilisateurs, lui permettant de pouvoir s'inspirer des recettes favorites des autres mais aussi de pouvoir consulter certaines de leurs informations.<br>

> ## L'utilisateur accédera aux profils des autres en cliquant sur une bulle affichant l'avatar de la personne.<br>

# Critères d'acceptation spécifiques à la US

> ## L'utilisateur ne peut accéder qu'aux informations publiques.<br>

> ## L'utilisateur peut reprendre des recettes favorites d'autres utilisateurs via un bouton.<br>

> ## La US respecte le design et la colorimétrie du projet

> ## La US passe les testes de vérifications généraux

> ## La US passe ses testes de vérifications spécifiques

# Prérequis 

> ## Nécessite une DB opérationnel avec API et endpoints mis en place, création d'un espace réservé aux commentaires, que ce soit dans la DB ou la page même du site

# Tâches techniques qui composent la US
> ## Création de la page web.<br>
> ## Gestion des requêtes à la DB.<br>
> ## Base de données opérationnelle pour stocker les recettes et informations des utlisateurs.<br>

# Estimation du temps de réalisation de la US
> ## Sur une échelle de 1 à 10 et comparé aux autres US, nous plaçons celle ci sur un niveau de difficulté de 7 pour le nombre de critères associés à celle-ci

**Comment by Hellisse** [comment]
Quel est la valeur de la US pour le client
Faible 

Description et objectif
l'utilisateur aura la possibilité de laisser un commentaire sur son impression d'une recette.



1.0 Création du compte :
En arrivant sur le site web, l'utilisateur peut se connecter via un formulaire en entrant son nom de compte et son mot de passe.

Le bouton de connexion sera situé en haut à droite de l'écran et ouvrira une bulle au centre affichant un formulaire.

Une fois connecté, l'utilisateur pourra cliquer en haut à droite pour modifier ses informations personnelles.

Critères d'acceptation spécifiques à la US
L'utilisateur à accès à la section "playlist" disponible dans la barre de navigation de l'application

La US respecte le design et la colorimétrie du projet

La US passe les testes de vérifications généraux

La US passe ses testes de vérifications spécifiques

Tâches techniques qui composent la US
Création de la page web
Endpoints API
Base de données opérationnelle pour stocker les identifiants des utlisateurs

Estimation du temps de réalisation de la US
Sur une échelle de 1 à 10 et comparé aux autres US, nous plaçons celle ci sur un niveau de difficulté de 6 pour le nombre de critères associés à celle-ci
